version: '2'
volumes:
  gems:
  mysql:
services:
  app:
    build: .
    volumes:
      - gems:/usr/local/bundle
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    command: rails s -p 3000 -b '0.0.0.0'
    environment:
      - TZ=America/Sao_Paulo

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    command: "--sql-mode='NO_ENGINE_SUBSTITUTION'"
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=traz-pra-mim_development
